### ISSUE TITLE
[Firefox] Main page never updates on click, always have to refresh

### ISSUE THREAD

**Issue by eristocrates** [kha-white/mokuro#100]
Take something as simple as clicking an already added manga. I see that the url has changed, but the page visually remains stuck on the main page. After a manual refresh, I'm taken to the url and everything works from there.

This occurs for literally every clickable ui element on the main page. This means I can't edit my profile nor upload manga from the main page because the dialog won't appear. I also can't search, sort, or change pages without manually refreshing to see the effects of clicking those buttons.

Below is the only console message from mokuro, if it helps
![image](https://github.com/kha-white/mokuro/assets/42102473/1e2248f7-f5d4-43bd-b4b2-50f410eee4ce)

**Comment by kha-white** [comment]
wrong repo, please move to https://github.com/ZXY101/mokuro-reader
