### ISSUE TITLE
Made Simple to Follow Guide 

### ISSUE THREAD

**Issue by wJosuke** [kha-white/mokuro#12]
Hey there, thanks for your work. This is very useful. Though the installation instructions (both the readme and the guide provided) were a little difficult to follow for those unfamiliar with github, python and this type of installation. I made a simple guide that I tried to make as simple as possible for people who would like to use this but have had some trouble.

Please let me know if there is anything I misunderstood, got wrong or if something else can be better simplified. Feel free to use this guide as you wish. 

[Guide](https://docs.google.com/document/d/1ddUINNHZoln6wXGAiGiVpZb4QPtonEy-jgrT1zQbXow/edit?usp=sharing)

**Comment by kha-white** [comment]
Hey, thanks. Seems mostly correct, though steps 2 and 3 are unnecessary.

**Comment by BigPuffDaddy** [comment]
> 

Sorry about that, I'm fairly unfamiliar with github. Do you only need to download the zip from the code drop down?

**Comment by kha-white** [comment]
You don't need to download any zip, when you run `pip3 install mokuro` this command downloads the package by itself.

**Comment by BigPuffDaddy** [comment]
> You don't need to download any zip, when you run `pip3 install mokuro` this command downloads the package by itself.

I understand now. I'll edit the guide with this.

**Comment by onxeyedkxng** [comment]
I've installed Mokuro successful but in your guide usage steps aren't working for me

**Comment by Juan0952** [comment]
> I've installed Mokuro successful but in your guide usage steps aren't working for me

Hey there, first of all, the format MUST BE JPG.
Put them all in once folder, example a folder called Japanese: 
folder 1: all jpg of manga 1
folder 2: all jpg of manga 2
folder 1 and folder 2 inside Japanese
!mokuro --as_one_file --disable_confirmation --parent_dir '/content/drive/MyDrive/Mangas/Japanese'
done

**Comment by onxeyedkxng** [comment]
> !mokuro --as_one_file --disable_confirmation --parent_dir '/content/drive/MyDrive/Mangas/Japanese'

Think the issue im having is mokuro isn't working as the command

I located where the file is when was installed with Pip. I made a PAth for that in System Variables but don't know if that's right. 

I'm unsure with this is what I need to do or a combination with OP's guide
