### ISSUE TITLE
Blank HTML File

### ISSUE THREAD

**Issue by SebyKebby** [kha-white/mokuro#15]
Hello, I recently followed Xelieu's guide on using Mokuro. I finished creating the HTML and OCR files for 18 volumes of Karakai Takagi-san but none of the HTML works. Done through google collab.

**Comment by kha-white** [comment]
Hi,
Do you have the folder with images in the same folder as the HTML? It should look similar to this:
```
vol1/
  000.jpg
  001.jpg
  ...
vol1.html
```

**Comment by SebyKebby** [comment]
I just tried doing it just now and it still doesn't work. Google Collab put the html files in the parent folder (manga folder) initially. Doing it your way still doesn't work

**Comment by SebyKebby** [comment]
wait no it shows text now, but the image doesn't appear
![image](https://user-images.githubusercontent.com/109518181/179652903-47f30c25-1e4d-402f-a349-70eb3f76e2d5.png)

**Comment by SebyKebby** [comment]
Oh sorry I'm stupid. I got it to work now. In the same folder... Sorry for wasting your time
