### ISSUE TITLE
Issues converting certain types of speech bubbles

### ISSUE THREAD

**Issue by wJosuke** [kha-white/mokuro#17]
Thanks again for your hard work.

I've encountered this issue a few times across 3 or so volumes of One Piece. When one bubble is above another, the text will get slightly jumbled, and the outputted text will alternate between the first box and second rather than showing each line of text in sequential order. 

![Mokuro Issue before](https://user-images.githubusercontent.com/65164569/180202515-8c4fc9a3-9762-43ca-9402-7d4cdb1513d2.JPG)
![Mokuro issue after](https://user-images.githubusercontent.com/65164569/180202510-f6ad77cf-1140-4874-a17a-543f6d035e07.JPG)

**Comment by kha-white** [comment]
Recent updates in [comic-text-detector ](https://github.com/dmMaze/comic-text-detector) seem to improve on this issue. I included them in 0.1.4 release.

![obraz](https://user-images.githubusercontent.com/22717958/200119778-db14bcfa-ca58-4aa8-a8ec-daec4b44377e.png)
![obraz](https://user-images.githubusercontent.com/22717958/200119787-beb9d2c8-2f28-49be-bf98-7893d78e02aa.png)
