### ISSUE TITLE
When trying to install error on Collecting torch=1.7.0 Killed 

### ISSUE THREAD

**Issue by OltiP2** [kha-white/mokuro#2]
its stops at killed and dosent install

**Comment by kha-white** [comment]
Please post the output from the console, either as a screenshot or copied text.

**Comment by OltiP2** [comment]
![Screenshot_2022-05-03_07-40-08](https://user-images.githubusercontent.com/97410429/166409064-6fce5a23-dd8d-4a21-8c23-d1c79daf446e.png)

i got the same issue as #3 tried to fix it then got this

**Comment by kha-white** [comment]
#3 should be resolved now, so maybe try again and let's see if this problem persists

**Comment by OltiP2** [comment]
Yeah it got fixed but if someone is having trouble where its randomly killing the install or says no space you can create a folder called tmp anywhere then before you type pip3 install mokuro type TMPDIR=/home/user/tmp/ replace the /home/user/tmp/ with the directory of the folder you created so for me it was "TMPDIR=/home/olti/tmp/ pip3 install mokuro"
