### ISSUE TITLE
Yomichan unable to use pop ups

### ISSUE THREAD

**Issue by noxxid3** [kha-white/mokuro#22]
Using Yomichan im able to get pop ups on the html, its working every else but this. Not entirely sure why its not working on the html file. 
But also would be cool if you also shared the text format you're using for the OCR for that pop up.

Edit: I was stupid and never enabled URL in the yomichan settings

**Comment by NolanGames3** [comment]
I am having this same issue. Yomichan will not pop up for me :(

**Comment by NolanGames3** [comment]
I am having this exact same issue. Yomichan won't pop up for me and enabling disenabling URL seems to make no difference. @noxxid3 which one exactly is it?
