### ISSUE TITLE
Manga missing - Blank pages

### ISSUE THREAD

**Issue by noxxid3** [kha-white/mokuro#24]
Not sure what is happening now, but it was working before and now everything is just broken. The pages do not come up only the words but its more of trying to find them. Not sure what happened or why
![image](https://user-images.githubusercontent.com/19700465/188331185-fa6eb10b-5bf1-4dda-b8e0-4c737a697c40.png)

**Comment by ChristopherFritz** [comment]
This appears to be opened from your web browser's cache folder, which will not see your images (because they are referenced with relative paths in the HTML file).

Does the issue occur if you open the HTML file from the folder where you ran Mokuro?
