### ISSUE TITLE
Sorts manga pages wrong way.

### ISSUE THREAD

**Issue by iGrizion** [kha-white/mokuro#25]
Have my manga sorted like this 
![image](https://user-images.githubusercontent.com/87672444/189973162-b7943a03-984e-41b4-9a17-959d651f2d06.png)
all pages in order, no issues, yet chapter 2 is page 340 or 380 and chapter 3 is page 333(?) 

i have 480 pages overall, chapter 10 happens right after chapter 1 yet it doesnt in my folder.

**Comment by kha-white** [comment]
Fixed in 0.1.4 release
