### ISSUE TITLE
Fails if file extensions are uppercase (.JPG or .PNG)

### ISSUE THREAD

**Issue by Tenpi** [kha-white/mokuro#26]
If the file extensions are uppercase (I've witnessed this a few times from downloaded manga) then the program will fail to find any of them. 

I can see there was a pull request (#11) for this, but it haven't been pushed to pip because it still fails with uppercase extensions. 

Installation with
```python
pip3 install mokuro
```

**Comment by ChristopherFritz** [comment]
It appears the last update to the package on PIP was on May 3rd, and the fix was merged after that on on July 17th.

The latest update to PIP can be seen here:

https://pypi.org/project/mokuro/#history

**Comment by kha-white** [comment]
Yeah, sorry about that. The fix is now included in 0.1.4 release.
