### ISSUE TITLE
Mokuro html lags after a while of being open..

### ISSUE THREAD

**Issue by evkaw** [kha-white/mokuro#29]
This is an issue I see more with manga with larger file sizes but it still happens on small files as well. The page just stops working when I try to hover over text, or even turn the page. I don't know why it happens, so I was wondering if there's anything I could do. Also, browser doesn't matter whether it be a fresh chrome account, one with extensions or even another browser like Vivaldi.

**Comment by kha-white** [comment]
I haven't observed that. Closing now, I'll reopen if more users report this issue.
