### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by hlawlovell** [kha-white/mokuro#34]
Getting an error while running mokuro. This is being thrown from line 38 in manga_page_ocr.py

AttributeError: 'NoneType' object has no attribute 'shape'
2022-11-23 22:34:43.023 | INFO     | mokuro.run:run:51 - Processed successfully: 0/1

**Comment by tak2hu** [comment]
does `comictextdetector.pt` exists? 

on linux it's in `~/.cache/manga-ocr`

**Comment by kha-white** [comment]
Closing as stale, let me know if you still have this problem
