### ISSUE TITLE
Manga pages out of order without leading zeroes

### ISSUE THREAD

**Issue by pedipanol** [kha-white/mokuro#35]
Went to process a manga that had volumes with and without leading zeroes on the page, the ones without got completely out of order (going 1 10-19 100 and so on instead)

Using a program to batch rename them fixed the issue, but I figured would be worth reporting if it's a fixable problem in the program itself

**Comment by kha-white** [comment]
What mokuro version are you using? This issue should be fixed since 0.1.4

**Comment by pedipanol** [comment]
It's 0.1.4! I'm using Xelieu's setup and running the install which should update it.

![image](https://user-images.githubusercontent.com/26771164/205076000-182f330d-d67b-4283-87c6-4cc263c0222f.png)

Maybe it's because of the google colab setup?

**Comment by kha-white** [comment]
I'll look into that
