### ISSUE TITLE
Manga pages blank  / HTML file too small

### ISSUE THREAD

**Issue by 2028chan** [kha-white/mokuro#36]
![sdfsdf](https://user-images.githubusercontent.com/121080393/208592809-37a6be12-8332-4cd7-9e56-1bc460b1d60d.PNG)

**Comment by saraqael-m** [comment]
Experiencing the same issue. It worked perfectly for me the first time I opened the file. But one day or so later it went blank and no matter how often I reopen it and with what browsers it's still blank. Has this issue been solved?

**Comment by KublaiKhan64** [comment]
Why is this closed??? I'm having the exact same issue after running everything as specified.
