### ISSUE TITLE
Yomichan doesn't work with Mokuro for me?

### ISSUE THREAD

**Issue by onxeyedkxng** [kha-white/mokuro#41]
I downloaded Yomichan on chrome but I cant get it to show up with mokuro using html.

The mouse and shift keys to get yomichan to pop up does not work but it works on a web url

So I think there's something wrong with my mokuro or how I set it up. But I downloaded Mokuro the basic way with python and pip and linked it to the path 100%. Didn't use pytorch or anaconda those exctra steps so im surprised its not working

If anyone had a similar issue and knows how to fix it, it'd be greatly appreciated :))

**Comment by Ceynou** [comment]
you already made an issue, don't open more.
Follow this [guide ](https://rentry.org/lazyXel)and there should be no issue
