### ISSUE TITLE
Could not find "cmake" executable!

### ISSUE THREAD

**Issue by ItsCheif** [kha-white/mokuro#43]
C:\Users\OWNER>pip3 install mokuro
Collecting mokuro
  Using cached mokuro-0.1.6-py3-none-any.whl (116 kB)
Collecting loguru
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting pyclipper
  Using cached pyclipper-1.3.0.post4-cp37-cp37m-win32.whl (85 kB)
Collecting mokuro
  Using cached mokuro-0.1.5-py3-none-any.whl (116 kB)
  Using cached mokuro-0.1.4-py3-none-any.whl (116 kB)
  Using cached mokuro-0.1.3-py3-none-any.whl (114 kB)
  Using cached mokuro-0.1.2-py3-none-any.whl (114 kB)
Collecting onnx-simplifier>=0.3.6
  Using cached onnx-simplifier-0.4.13.tar.gz (18.1 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 36, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\OWNER\AppData\Local\Temp\pip-install-jxl36kkh\onnx-simplifier_80104d44712b436a94ebb1f96f86acef\setup.py", line 65, in <module>
          assert CMAKE, 'Could not find "cmake" executable!'
      AssertionError: Could not find "cmake" executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ItsCheif** [comment]
I've downloaded "CMake" from this website but it hasn't had any effect https://cmake.org/download/

**Comment by kha-white** [comment]
Closing as stale, let me know if you still have this problem
