### ISSUE TITLE
package versions have conflicting dependencies

### ISSUE THREAD

**Issue by ItsCheif** [kha-white/mokuro#44]
This appeared both before and after installing Python 3.9. It occasionally shows up and occasionally doesn't.

C:\Users\OWNER>pip3 install mokuro
Collecting mokuro
  Using cached mokuro-0.1.6-py3-none-any.whl (116 kB)
Collecting loguru
  Using cached loguru-0.6.0-py3-none-any.whl (58 kB)
Collecting torchsummary
  Using cached torchsummary-1.5.1-py3-none-any.whl (2.8 kB)
Collecting opencv-python>=4.1.2
  Using cached opencv_python-4.7.0.68-cp37-abi3-win32.whl (28.2 MB)
Collecting mokuro
  Using cached mokuro-0.1.5-py3-none-any.whl (116 kB)
  Using cached mokuro-0.1.4-py3-none-any.whl (116 kB)
  Using cached mokuro-0.1.3-py3-none-any.whl (114 kB)
  Using cached mokuro-0.1.2-py3-none-any.whl (114 kB)
  Using cached mokuro-0.1.1-py3-none-any.whl (114 kB)
  Using cached mokuro-0.1.0-py3-none-any.whl (114 kB)
ERROR: Cannot install mokuro==0.1.0, mokuro==0.1.1, mokuro==0.1.2, mokuro==0.1.3, mokuro==0.1.4, mokuro==0.1.5 and mokuro==0.1.6 because these package versions have conflicting dependencies.

The conflict is caused by:
    mokuro 0.1.6 depends on torchvision>=0.8.1
    mokuro 0.1.5 depends on torchvision>=0.8.1
    mokuro 0.1.4 depends on torchvision>=0.8.1
    mokuro 0.1.3 depends on torchvision>=0.8.1
    mokuro 0.1.2 depends on torchvision>=0.8.1
    mokuro 0.1.1 depends on torchvision>=0.8.1
    mokuro 0.1.0 depends on torchvision>=0.8.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by Omar-Abdul-Azeez** [comment]
torch doesn't support python 3.11 at the moment try a previous version

**Comment by kha-white** [comment]
Closing as stale, let me know if you still have this problem
