### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by Llusper** [kha-white/mokuro#45]
Whenever I try the "mokuro directory" command, it gives me this error:
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by tak2hu** [comment]
i think the manga ocr model was not downloaded completely.

on Linux it's in `~/.cache/manga-ocr/` 

there should be `comictextdetector.pt`

delete it or continue downloading it using wget or something
