### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by ElaxDev** [kha-white/mokuro#49]
I think a dark mode would be a good addition since it would put less strain in the eyes, and it would be noticeable in longer reading sessions. Could be an option under settings that toggles dark/light mode.

it can be done with extensions right now but is not the ideal.

![imagen](https://user-images.githubusercontent.com/31047609/231813833-30521b7e-35b7-4895-96f3-e51ef26570df.png)

**Comment by SirGram** [comment]
It'd be a nice addition.

**Comment by ZXY101** [comment]
Not really a proper dark mode, but I've made a PR to let you select the background color.
(Not sure if this repos being maintained though)
