### ISSUE TITLE
Grey page visualised if opened in Kiwi Browser

### ISSUE THREAD

**Issue by nessn2** [kha-white/mokuro#51]
It would be great if Mokuro worked in Kiwi Browser, as this is the only way to use Yomichan on Android.

Mokuro working in Kiwi Browser means reading manga on an Android tablet with Yomichan.

I couldn't make it work in Kiwi Browser installed on my Motorola phone, neither on my Lenovo tablet. It looks like it's a Kiwi Browser issue.

**Comment by ZXY101** [comment]
Yeah, it looks like kiwi browser doesn't load any of the external files when you open the html file locally.

If you disable as single file and open the html, you'll notice the js and css isn't loaded.

I'd recommend you check out [jidoujisho](https://github.com/lrorpilla/jidoujisho) - it's got a reader specifically for mokuro. You can install your yomichan dictionaries and add cards directly to anki. It is essentially a yomichan equivalent for android.

Also I just opened up a PR to add a `mobile` flag to mokuro to generate more mobile friendly files, not sure if it's going to get merged anytime soon but just FYI.

**Comment by nessn2** [comment]
> Yeah, it looks like kiwi browser doesn't load any of the external files when you open the html file locally.
> 
> If you disable as single file and open the html, you'll notice the js and css isn't loaded.
> 
> I'd recommend you check out [jidoujisho](https://github.com/lrorpilla/jidoujisho) - it's got a reader specifically for mokuro. You can install your yomichan dictionaries and add cards directly to anki. It is essentially a yomichan equivalent for android.
> 
> Also I just opened up a PR to add a `mobile` flag to mokuro to generate more mobile friendly files, not sure if it's going to get merged anytime soon but just FYI.

I suspected that was the problem. I gave Kiwi permission to read local files but couldn't fix the problem.

I just tried jidoujisho on my tablet and I am speechless. This is exactly the tool that I needed for my Japanese readings. Thank you for bringing it to my attention! Mokuro and jidoujisho are projects that I will be happy to support.
