### ISSUE TITLE
Half/whole manga pages missing

### ISSUE THREAD

**Issue by noxxid3** [kha-white/mokuro#58]
I am not sure what exactly happened, this was working before but now im only seeing one page or none at all. 
![Screenshot_20230520_223337_Kiwi Browser](https://github.com/kha-white/mokuro/assets/19700465/f31c6195-1774-42dd-bb5a-f4bf84b5d8bb)
I had my tablet set up and working, it was reading everything correctly not sure if something messed up with kiwi browser but before it was working flawlessly but now im only seeing some pages, some are cut up and some are just completely missing.

**Comment by noxxid3** [comment]
seems to be a bug with it, the pages are there but are not 

https://github.com/kha-white/mokuro/assets/19700465/277feb03-f4dd-4764-9204-a53295b2874c

**Comment by kha-white** [comment]
Closing as old, please reopen if this issue persits.
