### ISSUE TITLE
Mokuro generated files on android 

### ISSUE THREAD

**Issue by novastar88** [kha-white/mokuro#59]
How to use mokuro HTML on android?
I'm using kiwi browser and don't see any images. Maybe there is smarter way (convert to other format)?

**Comment by NolanGames3** [comment]
This one is admittedly a very frustrating one, you need to download a files app that supports what you are trying to do, I recommend using File Manager +. It was free and works perfectly for me, then once you open the app, navigate to where your HTML file is stored and open that with kiwi. Enjoy your reading.

**Comment by YashaNoos** [comment]
If you are trying to use mokuro generated manga on android I would strongly recommend you to take a look at [jidoujisho](https://github.com/lrorpilla/jidoujisho) I have been playing with it this morning after discovering it on a discord and I'm amazed at how efficient and exhaustive it is.

**Comment by websorokinweb** [comment]
There is no problem with android. HTML file refers to images you downloaded. So if you copy the whole folder to android, it will work then
