### ISSUE TITLE
[REQUEST] Document all the UI keyboard controls in the README

### ISSUE THREAD

**Issue by diddy0dante** [kha-white/mokuro#67]
I was having a hard time figuring out the controls considering they aren't documented anywhere, and I'm wondering if there may be more I haven't found. it took me quite a while to find the pgup / pgdown controls for turning pages (my laptop doesn't have those keys).

I think it would be good to just put a list of all the keybinds in the readme.

**Comment by kha-white** [comment]
Closing because legacy HTML has been deprecated.
