### ISSUE TITLE
[REQUEST] Add option to create .html file without performing OCR

### ISSUE THREAD

**Issue by CFKaligula** [kha-white/mokuro#71]
The Mokuro html is a great way to read comics/magazines in image format it has a useful, simple UI. I wanted to quickly create a mokuro html file for a magazine, but it has to perform the OCR which took hours because it was a magazine with a lot of text.

Would be great if there is an option in the CI e.g --no-ocr so that it just creates the HTML document.

**Comment by CFKaligula** [comment]
I made the changes for this, I would like to open a branch to create a pull request but I don't have the rights for this...

**Comment by CFKaligula** [comment]
I created a [fork](https://github.com/CFKaligula/mokuro/tree/no-ocr)

**Comment by kha-white** [comment]
You can create a pull request from fork, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by CFKaligula** [comment]
> You can create a pull request from fork, see https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Thanks! I created one.
