### ISSUE TITLE
[Feature Request] Additional flags for reader default settings

### ISSUE THREAD

**Issue by blankaex** [kha-white/mokuro#76]
The web reader has a number of handy options (hiding the menu bar, first page as cover, changing background colour, etc.) however these options are not preserved in the browser. This introduces the friction of reconfiguring when re-opening an existing file or loading a new file.

It would be great if additional CLI flags could be implemented to generate html files with certain options enabled/disabled or specific values by default. Something along the lines of

```
$ mokuro --menubar-hidden=true --first-page-is-cover=true --background-color="c2c2c2" $dirname
```

**Comment by kha-white** [comment]
There are no plans to add new features to the legacy HTML format. Check out the new workflow including the [web reader](https://reader.mokuro.app/) and if there are GUI features that you'd like to request, you can file an issue in [mokuro-reader](https://github.com/ZXY101/mokuro-reader).

[More information on migration from legacy HTML to web reader](https://github.com/kha-white/mokuro?tab=readme-ov-file#legacy-html-vs-new-mokuro-format)
