### ISSUE TITLE
[Feature request] Larger max font size 

### ISSUE THREAD

**Issue by SpeedPeruna** [kha-white/mokuro#77]
On some titles, even the biggest font size is about 30% of the original text (which isn't that large to begin with). Would it be possible to add more options for it?

I don't know how to use github or technology in general so I'm sorry if I'm doing something weird or wrong.

**Comment by kha-white** [comment]
There are no plans to add new features to the legacy HTML format. Check out the new workflow including the [web reader](https://reader.mokuro.app/) and if there are GUI features that you'd like to request, you can file an issue in [mokuro-reader](https://github.com/ZXY101/mokuro-reader).

[More information on migration from legacy HTML to web reader](https://github.com/kha-white/mokuro?tab=readme-ov-file#legacy-html-vs-new-mokuro-format)
