### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by UngluedBike** [kha-white/mokuro#79]
AttributeError: 'NoneType' object has no attribute 'shape'
2023-11-14 15:29:22.910 | INFO     | mokuro.run:run:51 - Processed successfully: 0/1

Getting this error on a specific volume of yotsubato!, same page every time. All other volumes process successfully. I inspected the problematic page but I can't see anything different. I saw this error has been reported previously.

**Comment by kha-white** [comment]
Closing for now, if this issue persists please upload the problematic image and reopen.
