### ISSUE TITLE
Mouse scroll to scroll

### ISSUE THREAD

**Issue by reyaz006** [kha-white/mokuro#83]
I'm not getting the default usage method for when the image does not fit the screen. Mouse scroll is only zooming in/out.
I need to scroll it, and panning is not exactly intuitive.

I'd like mouse scroll to scroll up/down, and ctrl+scroll to zoom. If I wanted to pan I'd use middle mouse button.

**Comment by cedarhillgoods** [comment]
As a quick fix, you can use the mokuro-pan-scroll.js booklet from issue #4 .  Instructions for how to use are in the comments.  Latest download link is:

https://github.com/kha-white/mokuro/issues/4#issuecomment-1134164262

**Comment by kha-white** [comment]
There are no plans to add new features to the legacy HTML format. Check out the new workflow including the [web reader](https://reader.mokuro.app/) and if there are GUI features that you'd like to request, you can file an issue in [mokuro-reader](https://github.com/ZXY101/mokuro-reader).

[More information on migration from legacy HTML to web reader](https://github.com/kha-white/mokuro?tab=readme-ov-file#legacy-html-vs-new-mokuro-format)
