### ISSUE TITLE
Export all the text from each page

### ISSUE THREAD

**Issue by Teratani78** [kha-white/mokuro#85]
First of all, thank you for your job on makuro, it's very helpful :)

Is there any way to export all the OCR-ed text on a page.? Like being able to select all the text and copy and paste it instead of having to do it for each bubble.

Thank you for your answer :)

**Comment by vahid76758** [comment]
Hi

**Comment by vahid76758** [comment]
www.meunumerovirtual.com

**Comment by kha-white** [comment]
There are no plans to add new features to the legacy HTML format. Check out the new workflow including the [web reader](https://reader.mokuro.app/) and if there are GUI features that you'd like to request, you can file an issue in [mokuro-reader](https://github.com/ZXY101/mokuro-reader).

[More information on migration from legacy HTML to web reader](https://github.com/kha-white/mokuro?tab=readme-ov-file#legacy-html-vs-new-mokuro-format)
