### ISSUE TITLE
Directory setting instructions are unclear; Google Collab doesn't work

### ISSUE THREAD

**Issue by quietmansoath** [kha-white/mokuro#89]
I'm trying to set the path and I'm getting the following error:

![image](https://github.com/kha-white/mokuro/assets/46270221/4f9404f2-8ec5-4f6e-a75a-4f65433c173a)

I've tried several iterations of this directory and I'm not actually sure what to put. The instructions in the FAQ are rather vague.

My book is in a folder in my drive called "book". /book/ does not work. Using the full directory extension that's in my browser doesn't work. Unsure how to proceed.

**Comment by kha-white** [comment]
Did you run the previous cell?
```python
from google.colab import drive
drive.mount('/content/drive')
```
The window with Google Drive authorization should appear. If it was successful, then you should see your drive in the colab file browser:
![obraz](https://github.com/kha-white/mokuro/assets/22717958/133771f2-e676-4dc6-94f5-62b4c2b16fd7)
Then you should be able to find the `book` folder and copy its path in the context menu.

**Comment by quietmansoath** [comment]
Okay, so that's helpful and should be in the instructions, imo. It's not clear that I have to click the folder (was not expanded by default) or that I have to select the path from there.

So I did that, but now I'm stuck somewhere else. I run the program and it asks me to select yes or no. But I hit y on my keyboard, nothing happens. There is nothing to actually select on screen, no yes/no button. Not sure what to do here either.

![image](https://github.com/kha-white/mokuro/assets/46270221/0f7ed964-735c-456e-9241-4424defd874e)

**Comment by kha-white** [comment]
add `--disable_confirmation` to the command, like this:
`!mokuro --parent_dir "/content/drive/MyDrive/book" --disable_confirmation`

Sorry for the confusion, I agree that the instructions could be better.

**Comment by quietmansoath** [comment]
Thank you for your help and patience. I'm not a coder so I haven't had any idea what to do. I really want to get this working since I wasn't able to get past the error message installing it on my desktop; this is my only way to use your app.

That said, I was able to get it fully run (finally!) but of course once it's done, I still have no idea what to do. I'm not sure what to click on to actually open the files to be able to read them like in the demo.

**Comment by Interlinked** [comment]
> That said, I was able to get it fully run (finally!) but of course once it's done, I still have no idea what to do. I'm not sure what to click on to actually open the files to be able to read them like in the demo.

Where you listed your directory, a new file with the same name as your folder containing the images, should appear with the .html tag, just look around there
