### ISSUE TITLE
CBZ/CBR file support

### ISSUE THREAD

**Issue by blacktide082** [kha-white/mokuro#9]
It seems like CBZ/CBR files aren't currently supported, if you pass one of these file formats into `mokuro` you get a gnarly error.

To get around it, I just unzip the files and then run it on the directory, which works great. It's not a huge hassle so I will keep doing that for now, but I would love to see this feature in the future!

**Comment by Whitesttax** [comment]
Thanks blacktide082, I was trying to open a CBZ as well and it worked. If anyone is having trouble, right click the cbz file and open with winrar or equivalent software, then you can extract.
