### ISSUE TITLE
"ImportError: DLL load failed while importing fugashi: The specified module could not be found." even when downloading Python from official website

### ISSUE THREAD

**Issue by quietmansoath** [kha-white/mokuro#90]
Just tried to download and install mokuro to you on desktop (windows 10). Downloaded the latest Python, which is newer than 3.6.

Got the error in the title. Unsure how to proceed.

**Comment by Shpigorx** [comment]
I had same problem. 

My setup was with Python 3.10 on Win 10.
Python installed in Program Files for all users.
Mokuro was installed in Appdata, I added manually Appdata to PATH. And got same error.

Then I deleted this python and downloaded 3.9 (for test). Installed it with default settings for user (installation in localappdata, not Program Files). Installed mokuro again and all started to work.

**Comment by quietmansoath** [comment]
> I had same problem.
> 
> My setup was with Python 3.10 on Win 10. Python installed in Program Files for all users. Mokuro was installed in Appdata, I added manually Appdata to PATH. And got same error.
> 
> Then I deleted this python and downloaded 3.9 (for test). Installed it with default settings for user (installation in localappdata, not Program Files). Installed mokuro again and all started to work.

This helped, thanks. Just finally tried it. Uninstalled the python I already had, didn't check where it was though. Installed with no errors. Still can't get it working but it did install with no issues at least.
