### ISSUE TITLE
Longstrip/Webtoons comics mode

### ISSUE THREAD

**Issue by spacehamster** [kha-white/mokuro#94]
I'd like to see support for longstrip/webtoon comics in the reader / html output. It'd be nice to have an option to display all pages at once instead of only one page at a time as longstrip/webtoon comics don't really have a concept of pages.

**Comment by GunGunGun** [comment]
Due to the way mokuro display images which uses background CSS, it's pretty hard to change it behavior imo, I'm not sure maybe people who're good at CSS/JS can do, I tried but honestly unless I rewrite the reader code, I have no idea how to make background long strip.

**Comment by spacehamster** [comment]
Divs using background-url to display images does not pose any issues, it's just a matter of making disabling the display:none property and changing the layout to column instead of row. The challenge is polishing it up so it's user friendly, eg keeping place on page reload and switching between longstrip and paged modes, etc.

**Comment by kha-white** [comment]
I don't plan any major updates to the legacy HTML format. You can try requesting this feature in https://github.com/ZXY101/mokuro-reader
