### ISSUE TITLE
Mokuro using A LOT of CPU power when generating OCR?

### ISSUE THREAD

**Issue by venturiq** [kha-white/mokuro#97]
![NVIDIA_Share_N9YleVvRdF](https://github.com/kha-white/mokuro/assets/40541195/072e4055-f65c-4c98-b00f-faa3db9ec867)
![Taskmgr_qyyIS15rPD](https://github.com/kha-white/mokuro/assets/40541195/4587839f-8320-4301-84a3-d4a4922f2de7)
![Taskmgr_G9DwBzPjG7](https://github.com/kha-white/mokuro/assets/40541195/87b01852-6dbf-4b97-98f2-77ff3c873901)

Is this normal?

**Comment by venturiq** [comment]
Also, I just want to thank you guys for developing such an amazing piece of software!

**Comment by Kanjirito** [comment]
Yes this is completely normal. PyTorch didn't detect a CUDA capable GPU so it defaults to using your CPU (3rd line from the bottom) and it's just gonna use as much of it as it can.

**Comment by GunGunGun** [comment]
You're not using GPU, thus CPU is used for computing jobs
